export const FETCH_ITEMS_BY_ID_REQUEST = 'FETCH_ITEMS_BY_ID_REQUEST';
export const FETCH_ITEMS_BY_ID_SUCCESS = 'FETCH_ITEMS_BY_ID_SUCCESS';
export const FETCH_ITEMS_BY_ID_FAILURE = 'FETCH_ITEMS_BY_ID_FAILURE';
export const FETCH_ITEMS_BY_ID = [
  FETCH_ITEMS_BY_ID_REQUEST,
  FETCH_ITEMS_BY_ID_SUCCESS,
  FETCH_ITEMS_BY_ID_FAILURE
];

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUESTS';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const FETCH_ITEMS = [ 
  FETCH_ITEMS_REQUEST,
  FETCH_ITEMS_SUCCESS,
  FETCH_ITEMS_FAILURE 
];

export const OPEN_ITEMS_MODAL = 'OPEN_ITEMS_MODAL';
export const CLOSE_ITEMS_MODAL = 'CLOSE_ITEMS_MODAL';

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';