export const FETCH_ITEMS_BY_ID_REQUEST = 'FETCH_ITEMS_BY_ID_REQUEST';
export const FETCH_ITEMS_BY_ID_SUCCESS = 'FETCH_ITEMS_BY_ID_SUCCESS';
export const FETCH_ITEMS_BY_ID_FAILURE = 'FETCH_ITEMS_BY_ID_FAILURE';
export const FETCH_ITEMS_BY_ID = [
  FETCH_ITEMS_BY_ID_REQUEST,
  FETCH_ITEMS_BY_ID_SUCCESS,
  FETCH_ITEMS_BY_ID_FAILURE
];

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUESTS';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const FETCH_ITEMS = [ 
  FETCH_ITEMS_REQUEST,
  FETCH_ITEMS_SUCCESS,
  FETCH_ITEMS_FAILURE 
];

export const FETCH_CATEGORY_BY_ID_REQUEST = 'FETCH_CATEGORY_BY_ID_REQUEST';
export const FETCH_CATEGORY_BY_ID_SUCCESS = 'FETCH_CATEGORY_BY_ID_SUCCESS';
export const FETCH_CATEGORY_BY_ID_FAILURE = 'FETCH_CATEGORY_BY_ID_FAILURE';
export const FETCH_CATEGORY_BY_ID = [
  FETCH_CATEGORY_BY_ID_REQUEST,
  FETCH_CATEGORY_BY_ID_SUCCESS,
  FETCH_CATEGORY_BY_ID_FAILURE
];

export const FETCH_ALL_CATEGORIES_REQUEST = 'FETCH_ALL_CATEGORIES_REQUEST';
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS';
export const FETCH_ALL_CATEGORIES_FAILURE = 'FETCH_ALL_CATEGORIES_FAILURE';
export const FETCH_ALL_CATEGORIES = [ 
  FETCH_ALL_CATEGORIES_REQUEST,
  FETCH_ALL_CATEGORIES_SUCCESS,
  FETCH_ALL_CATEGORIES_FAILURE 
];


export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';